language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
      secure: MROn2agMmU0BTXdTha/Wgc/aCdoC0Zft59hR2eefCV1gLA6NCM7IZvfBdIACxAJebaYw85ePjLiy75MCu9kdo02/W3eejEKosHPLtrqxTVVPVsz5GVblz9mWyEEVbXpVcF69QvD0VBXAsc8hqcnccnrlzJoJkpuvzRMjCazA/2vjpNjLUswWejVJZPRtG8h7QCH2ASDFLsgSrA8xInGe/LWZs1XDHNHEEa3mvzfd0UFa/AQVV0BwqUuRA/LPq+1AnS+tWqQFqQlbiXwLnAyWLVNV4/2gsTshPrlOz60YxNCU1nyUiUbbsP+NIOaatZ+nWCeiN8AcgnwYAe1vjUfWr7IjjlGdpwV6Wu2d06blAC+lNQy10McSbjW6w2FrEeHb/bIDLqsN3akk1LPiDj7ztWydd70ExLNKiDljBrmJLyAJPMglt+ny6RtSQZCB025SXF5U1Kgv6OT83yckBSjdqBAEIJblLRnH1tLUf27+3c7nsR8rNhQLfttzALddtzqGAFC3Htvjf9O/rQV84ds60SDxOSpqJOIzCHZYfd+w3nxlJE6oiL9eknlVk5/pvEnI1BDRchQixxbNcyexIcs62gjg7mp8PsuvwMNN0ZpUps7FQ7AIqqsICVMM459vTvPwph3vS2uBPQMCnZBSVepqiYtCEmvCsZZEpaah1qFWxv0=
  file:
    - "emphasize.js"
    - "emphasize.min.js"
  on:
    tags: true
    node: '9.0'
